INSERT INTO OWNERS (HALTER_ID, ALTER, GESCHLECHT, STADTKREIS, STADTQUARTIER, RASSE1, RASSE1_MISCHLING, RASSE2, RASSE2_MISCHLING, RASSENTYP, GEBURTSJAHR_HUND, GESCHLECHT_HUND, HUNDEFARBE)
SELECT *
FROM CSVREAD('classpath:20210301_hundehalter.csv');

INSERT INTO BREEDS (RASSEN_TYP, HUNDE_RASSE)
SELECT *
FROM CSVREAD('classpath:20210301_zuordnungstabelle_hunderasse_hundetyp.csv');