INSERT INTO OWNERS (HALTER_ID, ALTER, GESCHLECHT, STADTKREIS, STADTQUARTIER)
SELECT HALTER_ID, ALTER, GESCHLECHT, STADTKREIS, STADTQUARTIER
FROM CSVREAD('classpath:owners.csv');

INSERT INTO DOGS (HALTER_ID, RASSE1, RASSE1_MISCHLING, RASSE2, RASSE2_MISCHLING, RASSENTYP, GEBURTSJAHR, GESCHLECHT, HUNDEFARBE)
SELECT HALTER_ID, RASSE1, RASSE1_MISCHLING, RASSE2, RASSE2_MISCHLING, RASSENTYP, GEBURTSJAHR_HUND, GESCHLECHT_HUND, HUNDEFARBE
FROM CSVREAD('classpath:dogs.csv');
